// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return windows; // Provide a dummy for linux to avoid crashing early
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'dummy_web',
    appId: 'dummy_web',
    messagingSenderId: 'dummy_web',
    projectId: 'dummy_web',
    authDomain: 'dummy_web',
    storageBucket: 'dummy_web',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'dummy_android',
    appId: 'dummy_android',
    messagingSenderId: 'dummy_android',
    projectId: 'dummy_android',
    storageBucket: 'dummy_android',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'dummy_ios',
    appId: 'dummy_ios',
    messagingSenderId: 'dummy_ios',
    projectId: 'dummy_ios',
    storageBucket: 'dummy_ios',
    iosBundleId: 'dummy_ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'dummy_macos',
    appId: 'dummy_macos',
    messagingSenderId: 'dummy_macos',
    projectId: 'dummy_macos',
    storageBucket: 'dummy_macos',
    iosBundleId: 'dummy_macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'dummy_windows',
    appId: 'dummy_windows',
    messagingSenderId: 'dummy_windows',
    projectId: 'dummy_windows',
    authDomain: 'dummy_windows',
    storageBucket: 'dummy_windows',
  );

}
