// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return windows; // Provide a dummy for linux to avoid crashing early
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVQsW_YPpRaL3cdyb3T40N2OO2DG1zSyw',
    appId: '1:657985869923:web:bc34e496c0bc285b010056',
    messagingSenderId: '657985869923',
    projectId: 'beanbase-app-2016',
    authDomain: 'beanbase-app-2016.firebaseapp.com',
    storageBucket: 'beanbase-app-2016.firebasestorage.app',
    measurementId: 'G-BV6W80DTQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'dummy_android',
    appId: 'dummy_android',
    messagingSenderId: 'dummy_android',
    projectId: 'dummy_android',
    storageBucket: 'dummy_android',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'dummy_ios',
    appId: 'dummy_ios',
    messagingSenderId: 'dummy_ios',
    projectId: 'dummy_ios',
    storageBucket: 'dummy_ios',
    iosBundleId: 'dummy_ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'dummy_macos',
    appId: 'dummy_macos',
    messagingSenderId: 'dummy_macos',
    projectId: 'dummy_macos',
    storageBucket: 'dummy_macos',
    iosBundleId: 'dummy_macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVQsW_YPpRaL3cdyb3T40N2OO2DG1zSyw',
    appId: '1:657985869923:web:19ba0c962bead53b010056',
    messagingSenderId: '657985869923',
    projectId: 'beanbase-app-2016',
    authDomain: 'beanbase-app-2016.firebaseapp.com',
    storageBucket: 'beanbase-app-2016.firebasestorage.app',
    measurementId: 'G-S89S6DMWDQ',
  );

}